#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    cat << EOF
$0: usage: ./cross-task [project-base-name] [task]

                 eg: ./cross-task enumeratumCirce test
EOF
    exit 1
fi

scalaVersions="2.10.6 2.11.8 2.12.1"
platforms="JS JVM"

name=$1
tasks=$2
command=""
for scalaVersion in $scalaVersions
do
    for platform in $platforms
    do
        command="${command}++${scalaVersion} "
        for task in ${tasks}
        do
          command="${command}${name}${platform}/${task} "
        done
    done
done

echo "Running: sbt ${command}"

sbt ${command}