#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    cat << EOF
$0: usage: ./cross-task [project-base-name] [task]

                 eg: ./cross-task enumeratumCirce test
EOF
    exit 1
fi

name=$1
task=$2
command="+${name}JS/$task +${name}JVM/$task"

echo "Running: sbt $command"

sbt ${command}