#!/usr/bin/env bash

# Warning, OSX-specific command hidden in between ;)
# SBT dies if we try to do them all in one go...
sbt "project circe-aggregate" +clean +publishSigned &&
say "Done 1" &&
say "Done 2" &&
sbt "project enumeratum-reactivemongo-bson" +clean +publishSigned &&
say "Done 3" &&
# sbt "project play-json-aggregate" +clean +publishSigned && # Doesn't work; 2.10 tries to publish a 2.13 POM
sbt "project enumeratumPlayJsonJVM" +clean +publishSigned &&
sbt "project enumeratumPlayJsonJS" +clean +publishSigned &&
say "Done 4" &&
sbt "project enumeratum-play" +clean +publishSigned &&
say "Done 5" &&
sbt "project argonaut-aggregate" +clean +publishSigned &&
say "Done 6" &&
sbt "project enumeratum-json4s" +clean +publishSigned &&
say "Done 7" &&
sbt "project scalacheck-aggregate" +clean +publishSigned &&
say "Done 8" &&
sbt "project quill-aggregate" +clean +publishSigned &&
say "All done"
