#!/usr/bin/env bash

# Warning, OSX-specific command hidden in between ;)
# SBT dies if we try to do them all in one go...
sbt "project circe-aggregate" +clean +publish-signed &&
say "Done 1" &&
sbt "project upickle-aggregate" +clean +publish-signed &&
say "Done 2" &&
sbt "project enumeratum-reactivemongo-bson" +clean +publish-signed &&
say "Done 3" &&
sbt "project enumeratum-play-json" +clean +publish-signed &&
say "Done 4" &&
sbt "project enumeratum-play" +clean +publish-signed &&
say "Done 5" &&
sbt "project enumeratum-argonaut" +clean +publish-signed &&
say "All done"